### PubSub Configuration in application.properties
# damu.pubsub.project.id=test
# logging.level.io.grpc.internal.ManagedChannelOrphanWrapper=OFF
# spring.cloud.gcp.pubsub.emulator-host=localhost:8085

# Start PubSub emulator at PORT 8085

# Create the topic damu consumes from
PUT http://localhost:8085/v1/projects/test/topics/GtfsRouteDispatcherTopic
###
# ... and the two it publishes to
PUT http://localhost:8085/v1/projects/test/topics/DamuExportGtfsStatusQueue
###
PUT http://localhost:8085/v1/projects/test/topics/MardukAggregateGtfsStatusQueue

###
# List topics to make sure they are created.
GET http://localhost:8085/v1/projects/test/topics

###
# Create the subscription named "GtfsRouteDispatcherTopic"
PUT http://localhost:8085/v1/projects/test/subscriptions/GtfsRouteDispatcherTopic
Content-Type: application/json

{ "topic": "projects/test/topics/GtfsRouteDispatcherTopic" }

###
# Create the subscription named "DamuExportGtfsStatusQueue"
PUT http://localhost:8085/v1/projects/test/subscriptions/DamuExportGtfsStatusQueue
Content-Type: application/json

{ "topic": "projects/test/topics/DamuExportGtfsStatusQueue" }

###
# Create the subscription named "MardukAggregateGtfsStatusQueue"
PUT http://localhost:8085/v1/projects/test/subscriptions/MardukAggregateGtfsStatusQueue
Content-Type: application/json

{ "topic": "projects/test/topics/MardukAggregateGtfsStatusQueue" }

###
# Start a NeTEx to GTFS conversion.
# data is the chouette referential in base64 encoding. (e.g rb_avi = "cmJfYXZp", rb_vyx ="cmJfdnl4",
# rb_rut="cmJfcnV0", rb_fin= "cmJfZmlu", rb_inn="cmJfaW5u")
POST http://localhost:8085/v1/projects/test/topics/GtfsRouteDispatcherTopic:publish
Content-Type: application/json

{
  "messages": [
    {
      "attributes": {
        "Action": "Export",
        "RutebankenCorrelationId": "CorrelationId",
        "RutebankenProviderId": "101",
        "RutebankenOriginalProviderId": "1"
      },
      "data": "cmJfdnl4"
    }
  ]
}

###
# Start a GTFS aggregation.
# data is the comma-separated file list in base64 encoding.
# cmJfYXZpLWFnZ3JlZ2F0ZWQtZ3Rmcy56aXA= = rb_avi-aggregated-gtfs.zip
# cmJfcnV0LWFnZ3JlZ2F0ZWQtZ3Rmcy56aXA= = rb_rut-aggregated-gtfs.zip
# cmJfYXZpLWFnZ3JlZ2F0ZWQtZ3Rmcy56aXAscmJfcnV0LWFnZ3JlZ2F0ZWQtZ3Rmcy56aXA= = rb_avi-aggregated-gtfs.zip,rb_rut-aggregated-gtfs.zip
POST http://localhost:8085/v1/projects/test/topics/GtfsRouteDispatcherTopic:publish
Content-Type: application/json

{
  "messages": [
    {
      "attributes": {
        "Action": "Aggregation",
        "RutebankenCorrelationId": "CorrelationId",
        "RutebankenProviderId": "101",
        "RutebankenOriginalProviderId": "1"
      },
      "data": "cmJfYXZpLWFnZ3JlZ2F0ZWQtZ3Rmcy56aXAscmJfcnV0LWFnZ3JlZ2F0ZWQtZ3Rmcy56aXA="
    }
  ]
}
