common:
  env: dev
  replicas: 1
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx15000m -Xss512k -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:ActiveProcessorCount=2
        -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote.port=9999  -Dcom.sun.management.jmxremote.rmi.port=9998 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1

damu:
  gtfs:
    export:
      stayseated: true
gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: ent-marduk-dev

  marduk:
    bucketName: marduk-dev
    gtfsFolder: outbound
  damu:
    bucketName: damu-dev

stopplaceRegistryUrl: https://api.dev.entur.io/stop-places/v1/read