common:
  env: prd
  replicas: 1
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx15000m -Xss512k -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:ActiveProcessorCount=2
        -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8

damu:
  gtfs:
    export:
      stayseated: false
gcp:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: ent-marduk-prd

  marduk:
    bucketName: marduk-production
    gtfsFolder: outbound

stopplaceRegistryUrl: https://api.entur.io/stop-places/v1/read