env: dev
replicas: 1

damu:
  gtfs:
    export:
      stayseated: true
gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev

  marduk:
    bucketName: marduk-dev
    gtfsFolder: outbound

monitoringEnabled: true
