env: prod
replicas: 1

damu:
  gtfs:
    export:
      stayseated: false

gcp:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod

  marduk:
    bucketName: marduk-production
    gtfsFolder: outbound

monitoringEnabled: false
