env: test
replicas: 1

damu:
  gtfs:
    export:
      stayseated: false

gcp:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test

  marduk:
    bucketName: marduk-test
    gtfsFolder: outbound

monitoringEnabled: true
