common:
  app: damu
  shortname: damu
  team: ror
  ingress:
    enabled: false
  service:
    externalPort: 8080
    internalPort: 8080
  container:
    labels: { customLogRetention: enabled }
    forceReplicas: 1
    image: <+artifacts.primary.image>
    cpu: 2
    memory: 18000
    memoryLimit: 20000
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: damu-application
        name: application-config
  postgres:
    enabled: false
  configmap:
    data:
      TZ: Europe/Oslo
    enabled: true
    toEnv: true