image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: 1000m
  memLimit: 10000Mi
  cpuRequest: 1000m
  memRequest: 8000Mi
  xmx: 7000m
