image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: 1000m
  memLimit: 15000Mi
  cpuRequest: 1000m
  memRequest: 10000Mi
  xmx: 9000m
