image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: 1000m
  memLimit: 2000Mi
  cpuRequest: 1000m
  memRequest: 1800Mi
  xmx: 1600m
