apiVersion: v1
data:
  application.properties: |+

    # Spring
    spring.main.sources=no.entur.damu
    spring.profiles.active=gcs-blobstore
    server.port={{ .Values.service.http.internalPort }}

    # Damu
    damu.netex.stop.cache.refresh.quartz.trigger:?cron=0+0+3+?+*+*

    # Camel
    camel.springboot.name=damu
    camel.dataformat.json-jackson.module-refs=jacksonJavaTimeModule
    camel.cluster.kubernetes.enabled=true
    camel.cluster.kubernetes.cluster-labels[app]=damu
    camel.cluster.kubernetes.config-map-name=damu-leaders
    camel.servlet.mapping.context-path=/services/*
    # the Camel shutdown timeout must be shorter than the Kubernetes terminationGracePeriod
    damu.shutdown.timeout=25

    # PubSub
    damu.pubsub.project.id={{ .Values.gcp.pubsubProjectId }}
    spring.cloud.gcp.project-id=${damu.pubsub.project.id}
    camel.component.google-pubsub.service-account-key=file:/etc/damu-service-account/credentials.json

    # Blobstore
    blobstore.gcs.project.id={{ .Values.gcp.blobstoreProjectId }}
    blobstore.gcs.credential.path=/etc/damu-service-account/credentials.json
    blobstore.gcs.marduk.container.name={{ .Values.gcp.marduk.bucketName }}

    # Actuator
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus

    # Logging
    logging.level.no.entur=INFO
    logging.level.org.apache=INFO
    logging.config=classpath:logback.xml
    logging.level.org.apache.camel.component.http.HttpComponent=WARN
    logging.level.no.entur.damu=DEBUG

kind: ConfigMap
metadata:
  name: {{ template "damu.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
