common:
  env: prd
  replicas: 1

damu:
  gtfs:
    export:
      stayseated: false
gcp:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: ent-marduk-prd

  marduk:
    bucketName: marduk-production
    gtfsFolder: outbound

